#!/usr/bin/env bash

# litchi development only
# git remote add upstream git@github.com:laravel/laravel.git

git remote add upstream git@github.com:litchi-io/litchi-laravel.git

composer install
cp .env.example .env
php artisan key:generate

cd public && bash _install && cd ..
