#!/usr/bin/env bash

cd .. && git clone git@github.com:litchi-io/litchi-sass.git litchi-sass-temp

cp -rv litchi-sass-temp/css litchi-laravel/public
cp -rv litchi-sass-temp/fonts litchi-laravel/public
cp -rv litchi-sass-temp/images litchi-laravel/public
cp -rv litchi-sass-temp/js litchi-laravel/public

cp -v litchi-sass-temp/favicon.ico litchi-sass-temp/screen-icon.png litchi-sass-temp/gulpfile.js litchi-sass-temp/_install litchi-laravel/public
cp -v litchi-sass-temp/package.json litchi-sass-temp/bower.json litchi-sass-temp/tsd.json litchi-sass-temp/gulpfile.js litchi-laravel/public

sudo rm -r litchi-sass-temp && cd litchi-laravel

printf "\n\nDependencies successfully copied over to /public\n\n"

git fetch upstream
git merge upstream/master